on:
  issues:
    types: [opened]
    
jobs:
  create_issue:
    runs-on: ubuntu-latest
    name: Create bounty
    steps:
      - name: create bounty step
        id: bounty
        uses: SolanaDevMill/CreateBountyAction@main
        with:
          wallet-key: ${{ secrets.DEV_MILL_KEY }}
        
