on:
  pull_request:
    types: [closed]

jobs:
  release_bounty_job:
    runs-on: ubuntu-latest
    name: release bounty
    steps:
      - name: release bounty
        uses: SolanaDevMill/ReleaseBountyAction@main
        with:
          wallet-key: ${{ secrets.DEVMILLKEY }}
      
